#!/bin/bash

ext = $1

echo ../res/coombe/clips/$1/g3 
echo tests/coombe_$1/g3_trajectory.txt

./trace.py ../res/coombe/clips/$1/g3 tests/coombe_$1/g3_trajectory.txt

./trace.py ../res/coombe/clips/$1/lumix tests/coombe_$1/lumix_trajectory.txt


